spring:
  application:
    name: yu-ai-agent
  datasource:
    url: jdbc:mysql://localhost:3306/yupi?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.145.128
      port: 6379
      password: 123456
  ai:
    dashscope:
      # 需要替换为你自己的 key
      api-key: sk-9cc08c87fa4f4b25938998f2dcc77477
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
# 临时注释掉，便于大家开发调试和部署（实际需要启动 MCP 服务）
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json

# PGVector 专属数据源（与主数据源 MySQL 隔离）
app:
  pgvector:
    datasource:
      url: jdbc:postgresql://localhost:5432/yu_agent
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.yuaiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchAPI
search-api:
  # 需要替换为你自己的 key
  api-key: rKds2umhXLoNFVPvMYmSKQQe
# 修改日志级别，查看 Spring AI 更多调用细节
logging:
  level:
    org.springframework.ai: DEBUG